version: '3'

services:

  action_server:
    image: rasa/rasa_core_sdk:latest
    networks: ['rasa-network']
    ports:
      - "5055:5055"
    volumes:
      - "./rasa-app-data/actions:/app/actions"

  rasa_nlu:
    image: rasa/rasa_nlu:0.13.7-full
    networks: ['rasa-network']
    ports:
      - "5000:5000"
    volumes:
      - "./rasa-app-data/models/current/nlu:/app/projects"
      - "./rasa-app-data/project/:/app/config"
      - "./rasa-app-data/logs:/app/logs"
    command:
      - start
      # - --pre_load
      # - all
      # this is gonna be annoying since yaml doesn't support block comments ... anyway
      # ideally we can pre-load all models into memory before starting rasa ui BUT
      # it looks like there is a bug where this only works if the folder directory is specifically in this way:
      # /projects
      #     -- <project name>
      #             -- <model_date_time> (instead of <project_name>_date_time which rasa nlu will do by default)
      # maybe we can run a script to rename the models at `docker-compse up`?
      - --path
      - /app/projects
      - --write
      - /app/logs/nlu
      - --response_log
      - /app/logs/nlu
      - --config
      - /app/config/nlu_config.yml
      - --debug
      - --verbose

  rasa_core:
    image: rasa/rasa_core:0.12.1
    networks: ['rasa-network']
    ports:
      - "5005:5005"
    depends_on:
      - "rasa_nlu"
      - "action_server"
    volumes:
      - "./rasa-app-data/models/current/dialogue:/app/model"
      - "./rasa-app-data/config:/app/config"
      - "./rasa-app-data/project:/app/project"
    command:
      - start
      - -d
      - ./model
      - -c
      - rest
      - -u
      - current/nlu
      - --endpoints
      - config/endpoints.yml

  postgres:
    image: postgres:11
    networks: ['rasa-network']
    ports:
      - "5432:5432"
    volumes:
      - "$PWD/resources/database/10-initdb.sh:/docker-entrypoint-initdb.d/10-initdb.sh"
      - "$PWD/resources/database/dbcreate.sql:/dbcreate.sql"
      - "rasauidata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "rasaui"
      POSTGRES_DB: "rasaui"

  rasa_ui:       
    image: paschmann/rasa-ui:latest
    networks: ['rasa-network']
    ports:
      - "5001:5001"
    depends_on:
      - "rasa_nlu"
      - "postgres"
    environment:
      rasanluendpoint: "http://rasa_nlu:5000"
      rasacoreendpoint: "http://rasa_core:5005"
      postgresserver: "postgres://postgres:rasaui@postgres:5432/rasaui"

networks: {rasa-network: {}}
volumes: {rasauidata:{}}
